/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ContactPagina = {
  _id: string;
  _type: "contactPagina";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  introTitel?: string;
  introOmschrijving?: string;
  email?: string;
  facebookUrl?: string;
  instagramUrl?: string;
  sporthallen?: Array<{
    naam?: string;
    adres?: string;
    extra?: string;
    _key: string;
  }>;
  formulierTitel?: string;
  formulierOmschrijving?: string;
  formulierUrl?: string;
  formulierKnopLabel?: string;
};

export type LidWordenPagina = {
  _id: string;
  _type: "lidWordenPagina";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  lidTitel?: string;
  lidOmschrijving?: string;
  lidTwizzitUrl?: string;
  schoolTitel?: string;
  schoolOmschrijving?: string;
  schoolTwizzitUrl?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Sponsor = {
  _id: string;
  _type: "sponsor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  type?: "hoofdsponsor" | "sponsor";
  omschrijving?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  websiteUrl?: string;
  order?: number;
  tier?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type TeamReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "team";
};

export type ClubDocument = {
  _id: string;
  _type: "clubDocument";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: "reglement" | "formulier" | "verslag" | "andere";
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  publishedAt?: string;
  team?: TeamReference;
  description?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  eventType?: "stage" | "event";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  startDate?: string;
  endDate?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  twizzitUrl?: string;
  status?: "open" | "bijna_volzet" | "volzet";
};

export type Team = {
  _id: string;
  _type: "team";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  volgorde?: number;
  name?: string;
  slug?: Slug;
  basketVlaanderenId?: string;
  teamPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  coachName?: string;
  assistantCoach?: string;
  trainingHours?: Array<{
    day?:
      | "maandag"
      | "dinsdag"
      | "woensdag"
      | "donderdag"
      | "vrijdag"
      | "zaterdag"
      | "zondag";
    startTime?: string;
    endTime?: string;
    location?: string;
    _type: "trainingSlot";
    _key: string;
  }>;
  categorie?: "bovenbouw" | "onderbouw";
  description?: string;
  category?: string;
  order?: number;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  excerpt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ContactPagina
  | LidWordenPagina
  | SanityImageAssetReference
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Sponsor
  | SanityFileAssetReference
  | TeamReference
  | ClubDocument
  | Event
  | Team
  | Post
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "post"] | order(publishedAt desc) {    _id, title, slug, publishedAt, excerpt, mainImage  }
export type ALL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  excerpt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    _id, title, slug, publishedAt, excerpt, mainImage, body  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  excerpt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_TEAMS_QUERY
// Query: *[_type == "team"] | order(volgorde asc, name asc) {    _id, name, slug, categorie, teamPhoto, basketVlaanderenId, coachName, assistantCoach  }
export type ALL_TEAMS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  categorie: "bovenbouw" | "onderbouw" | null;
  teamPhoto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  basketVlaanderenId: string | null;
  coachName: string | null;
  assistantCoach: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: TEAM_BY_SLUG_QUERY
// Query: *[_type == "team" && slug.current == $slug][0] {    _id, name, slug, categorie, teamPhoto, basketVlaanderenId, coachName, assistantCoach, trainingHours, description  }
export type TEAM_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  categorie: "bovenbouw" | "onderbouw" | null;
  teamPhoto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  basketVlaanderenId: string | null;
  coachName: string | null;
  assistantCoach: string | null;
  trainingHours: Array<{
    day?:
      | "dinsdag"
      | "donderdag"
      | "maandag"
      | "vrijdag"
      | "woensdag"
      | "zaterdag"
      | "zondag";
    startTime?: string;
    endTime?: string;
    location?: string;
    _type: "trainingSlot";
    _key: string;
  }> | null;
  description: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: TEAMS_FOR_NAV_QUERY
// Query: *[_type == "team"] | order(volgorde asc, name asc) {    _id, name, "slug": slug.current, categorie  }
export type TEAMS_FOR_NAV_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  categorie: "bovenbouw" | "onderbouw" | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: TEAM_BY_VBL_ID_QUERY
// Query: *[_type == "team" && basketVlaanderenId == $vblId][0]
export type TEAM_BY_VBL_ID_QUERY_RESULT = {
  _id: string;
  _type: "team";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  volgorde?: number;
  name?: string;
  slug?: Slug;
  basketVlaanderenId?: string;
  teamPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  coachName?: string;
  assistantCoach?: string;
  trainingHours?: Array<{
    day?:
      | "dinsdag"
      | "donderdag"
      | "maandag"
      | "vrijdag"
      | "woensdag"
      | "zaterdag"
      | "zondag";
    startTime?: string;
    endTime?: string;
    location?: string;
    _type: "trainingSlot";
    _key: string;
  }>;
  categorie?: "bovenbouw" | "onderbouw";
  description?: string;
  category?: string;
  order?: number;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_TEAM_SLUGS_QUERY
// Query: *[_type == "team"]{ "slug": slug.current }
export type ALL_TEAM_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_EVENTS_QUERY
// Query: *[_type == "event"] | order(startDate asc) {    _id, title, slug, eventType, startDate, endDate, status, twizzitUrl, image  }
export type ALL_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  eventType: "event" | "stage" | null;
  startDate: string | null;
  endDate: string | null;
  status: "bijna_volzet" | "open" | "volzet" | null;
  twizzitUrl: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: UPCOMING_EVENTS_QUERY
// Query: *[_type == "event" && startDate >= $now] | order(startDate asc) {    _id, title, slug, eventType, startDate, endDate, status, twizzitUrl, image  }
export type UPCOMING_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  eventType: "event" | "stage" | null;
  startDate: string | null;
  endDate: string | null;
  status: "bijna_volzet" | "open" | "volzet" | null;
  twizzitUrl: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: EVENT_BY_SLUG_QUERY
// Query: *[_type == "event" && slug.current == $slug][0] {    _id, title, slug, eventType, startDate, endDate, description, twizzitUrl, status, image  }
export type EVENT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  eventType: "event" | "stage" | null;
  startDate: string | null;
  endDate: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  twizzitUrl: string | null;
  status: "bijna_volzet" | "open" | "volzet" | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: EVENTS_BY_TYPE_QUERY
// Query: *[_type == "event" && eventType == $type] | order(startDate asc) {    _id, title, slug, startDate, endDate, status, twizzitUrl, image  }
export type EVENTS_BY_TYPE_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  startDate: string | null;
  endDate: string | null;
  status: "bijna_volzet" | "open" | "volzet" | null;
  twizzitUrl: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: HOMEPAGE_EVENTS_QUERY
// Query: *[_type == "event" && status == "open" && startDate >= $now] | order(startDate asc) [0..1] {    _id, title, slug, eventType, startDate, endDate, twizzitUrl, image  }
export type HOMEPAGE_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  eventType: "event" | "stage" | null;
  startDate: string | null;
  endDate: string | null;
  twizzitUrl: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: HOMEPAGE_POSTS_QUERY
// Query: *[_type == "post"] | order(publishedAt desc) [0..2] {    _id, title, slug, publishedAt, excerpt, mainImage  }
export type HOMEPAGE_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  excerpt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0] {    _id, title, slug, excerpt, content  }
export type PAGE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_PAGE_SLUGS_QUERY
// Query: *[_type == "page"]{ "slug": slug.current }
export type ALL_PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_SPONSORS_QUERY
// Query: *[_type == "sponsor"] | order(order asc, name asc) {    _id, name, logo, websiteUrl, type, omschrijving, tier  }
export type ALL_SPONSORS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  websiteUrl: string | null;
  type: "hoofdsponsor" | "sponsor" | null;
  omschrijving: string | null;
  tier: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: LID_WORDEN_QUERY
// Query: *[_type == "lidWordenPagina"][0] {    lidTitel, lidOmschrijving, lidTwizzitUrl,    schoolTitel, schoolOmschrijving, schoolTwizzitUrl  }
export type LID_WORDEN_QUERY_RESULT = {
  lidTitel: string | null;
  lidOmschrijving: string | null;
  lidTwizzitUrl: string | null;
  schoolTitel: string | null;
  schoolOmschrijving: string | null;
  schoolTwizzitUrl: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: CONTACT_PAGINA_QUERY
// Query: *[_type == "contactPagina"][0] {    introTitel, introOmschrijving,    email, facebookUrl, instagramUrl,    sporthallen,    formulierTitel, formulierOmschrijving, formulierUrl, formulierKnopLabel  }
export type CONTACT_PAGINA_QUERY_RESULT = {
  introTitel: string | null;
  introOmschrijving: string | null;
  email: string | null;
  facebookUrl: string | null;
  instagramUrl: string | null;
  sporthallen: Array<{
    naam?: string;
    adres?: string;
    extra?: string;
    _key: string;
  }> | null;
  formulierTitel: string | null;
  formulierOmschrijving: string | null;
  formulierUrl: string | null;
  formulierKnopLabel: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_DOCUMENTS_QUERY
// Query: *[_type == "clubDocument"] | order(publishedAt desc) {    _id, title, slug, category, file, publishedAt, team->{ name }  }
export type ALL_DOCUMENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  category: "andere" | "formulier" | "reglement" | "verslag" | null;
  file: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  } | null;
  publishedAt: string | null;
  team: {
    name: string | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "post"] | order(publishedAt desc) {\n    _id, title, slug, publishedAt, excerpt, mainImage\n  }': ALL_POSTS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0] {\n    _id, title, slug, publishedAt, excerpt, mainImage, body\n  }': POST_BY_SLUG_QUERY_RESULT;
    '*[_type == "team"] | order(volgorde asc, name asc) {\n    _id, name, slug, categorie, teamPhoto, basketVlaanderenId, coachName, assistantCoach\n  }': ALL_TEAMS_QUERY_RESULT;
    '*[_type == "team" && slug.current == $slug][0] {\n    _id, name, slug, categorie, teamPhoto, basketVlaanderenId, coachName, assistantCoach, trainingHours, description\n  }': TEAM_BY_SLUG_QUERY_RESULT;
    '*[_type == "team"] | order(volgorde asc, name asc) {\n    _id, name, "slug": slug.current, categorie\n  }': TEAMS_FOR_NAV_QUERY_RESULT;
    '*[_type == "team" && basketVlaanderenId == $vblId][0]': TEAM_BY_VBL_ID_QUERY_RESULT;
    '*[_type == "team"]{ "slug": slug.current }': ALL_TEAM_SLUGS_QUERY_RESULT;
    '*[_type == "event"] | order(startDate asc) {\n    _id, title, slug, eventType, startDate, endDate, status, twizzitUrl, image\n  }': ALL_EVENTS_QUERY_RESULT;
    '*[_type == "event" && startDate >= $now] | order(startDate asc) {\n    _id, title, slug, eventType, startDate, endDate, status, twizzitUrl, image\n  }': UPCOMING_EVENTS_QUERY_RESULT;
    '*[_type == "event" && slug.current == $slug][0] {\n    _id, title, slug, eventType, startDate, endDate, description, twizzitUrl, status, image\n  }': EVENT_BY_SLUG_QUERY_RESULT;
    '*[_type == "event" && eventType == $type] | order(startDate asc) {\n    _id, title, slug, startDate, endDate, status, twizzitUrl, image\n  }': EVENTS_BY_TYPE_QUERY_RESULT;
    '*[_type == "event" && status == "open" && startDate >= $now] | order(startDate asc) [0..1] {\n    _id, title, slug, eventType, startDate, endDate, twizzitUrl, image\n  }': HOMEPAGE_EVENTS_QUERY_RESULT;
    '*[_type == "post"] | order(publishedAt desc) [0..2] {\n    _id, title, slug, publishedAt, excerpt, mainImage\n  }': HOMEPAGE_POSTS_QUERY_RESULT;
    '*[_type == "page" && slug.current == $slug][0] {\n    _id, title, slug, excerpt, content\n  }': PAGE_BY_SLUG_QUERY_RESULT;
    '*[_type == "page"]{ "slug": slug.current }': ALL_PAGE_SLUGS_QUERY_RESULT;
    '*[_type == "sponsor"] | order(order asc, name asc) {\n    _id, name, logo, websiteUrl, type, omschrijving, tier\n  }': ALL_SPONSORS_QUERY_RESULT;
    '*[_type == "lidWordenPagina"][0] {\n    lidTitel, lidOmschrijving, lidTwizzitUrl,\n    schoolTitel, schoolOmschrijving, schoolTwizzitUrl\n  }': LID_WORDEN_QUERY_RESULT;
    '*[_type == "contactPagina"][0] {\n    introTitel, introOmschrijving,\n    email, facebookUrl, instagramUrl,\n    sporthallen,\n    formulierTitel, formulierOmschrijving, formulierUrl, formulierKnopLabel\n  }': CONTACT_PAGINA_QUERY_RESULT;
    '*[_type == "clubDocument"] | order(publishedAt desc) {\n    _id, title, slug, category, file, publishedAt, team->{ name }\n  }': ALL_DOCUMENTS_QUERY_RESULT;
  }
}
